---
- name: Install and Configure Minikube
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure dependencies are installed (Ubuntu/Debian)
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - apt-transport-https
        - ca-certificates
        - software-properties-common
      when: ansible_os_family == 'Debian'

    - name: Ensure dependencies are installed (CentOS/RHEL)
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      when: ansible_os_family == 'RedHat'

    - name: Download Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
      when: ansible_os_family in ['Debian', 'RedHat']

    - name: Download kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      when: ansible_os_family in ['Debian', 'RedHat']

    - name: Start Minikube
      command: minikube start
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"

    - name: Set up kubectl context
      command: minikube update-context
