---
- name: Setup Minikube on Ubuntu
  hosts: local
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - conntrack
          - socat
          - ebtables
          - docker.io
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ lookup('env','USER') }}"
        groups: docker
        append: yes

    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Install Minikube
      command: chmod +x /usr/local/bin/minikube

    - name: Create a shell script to start Minikube
      copy:
        dest: /home/{{ lookup('env','USER') }}/start_minikube.sh
        content: |
          #!/bin/bash
          newgrp docker <<EONG
          minikube start --driver=docker
          EONG
      mode: '0755'
      become: no

    - name: Run the shell script to start Minikube
      command: /home/{{ lookup('env','USER') }}/start_minikube.sh
      become: no

    - name: Enable kubectl bash completion
      lineinfile:
        path: /home/{{ lookup('env','USER') }}/.bashrc
        line: 'source <(kubectl completion bash)'
      become: no
      become_user: "{{ lookup('env','USER') }}"

    - name: Install kubectl alias
      lineinfile:
        path: /home/{{ lookup('env','USER') }}/.bashrc
        line: 'alias k=kubectl'
      become: no
      become_user: "{{ lookup('env','USER') }}"

    - name: Apply bash completion
      shell: . /home/{{ lookup('env','USER') }}/.bashrc
      args:
        executable: /bin/bash
      become: no
      become_user: "{{ lookup('env','USER') }}"
